services:
  app:
    build: .
    ports:
      - "${PORT:-3050}:3050"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - EXTERNAL_URL=${EXTERNAL_URL:-http://localhost:3050}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/api/webhooks/polar/health"]
      interval: 30s
      timeout: 10s
      retries: 3
