services:
  app:
    build:
      context: .
      target: builder # Use development-ready image
    ports:
      - "3050:3050"
    volumes:
      # Mount source code for hot reloading, excluding node_modules and .next
      - .:/app:delegated
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3050
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    # Health check to ensure container is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:3050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
