services:
  app:
    build: .
    ports:
      - "3050:3050"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3050
      - NEXT_TELEMETRY_DISABLED=1
    tty: true
    stdin_open: true
